### ISSUE TITLE
Installation issue: FileNotFoundError: python/version.txt

### ISSUE THREAD

**Issue by reshef-rt** [flashlight/text#76]
### Bug Description
Running `pip install flashlight-text` and seeing this error.

#### Reproduction Steps
```
Collecting flashlight-text
  Using cached flashlight-text-0.0.4.tar.gz (59 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/st/hb0c30bj3_zf0v8p31pb79m00000gn/T/pip-install-3ymyt6ga/flashlight-text_1ae296a55a9d4fb89daaec0ba0226f7a/setup.py", line 237, in <module>
          main()
        File "/private/var/folders/st/hb0c30bj3_zf0v8p31pb79m00000gn/T/pip-install-3ymyt6ga/flashlight-text_1ae296a55a9d4fb89daaec0ba0226f7a/setup.py", line 191, in main
          with open(version_txt) as f:
               ^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/st/hb0c30bj3_zf0v8p31pb79m00000gn/T/pip-install-3ymyt6ga/flashlight-text_1ae296a55a9d4fb89daaec0ba0226f7a/bindings/python/version.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Platform and Hardware
Macbook Pro M3

**Comment by sahaj-wispr** [comment]
Were you able to figure out the solution to this installation?

**Comment by jacobkahn** [comment]
Apologies, I've been off the grid. Issue here is that a Python 3.12 wheel hasn't been published, and the sdist build doesn't include the version file, so that fails. I will push fixes to both of these. Thanks for flagging.

**Comment by sahaj-wispr** [comment]
Thank you so much - greatly appreciate it. Please let me know once those fixes are pushed!

**Comment by kgoba** [comment]
I have Python `3.10.11` here and getting the same error while doing pip install in a clean venv.

**Comment by masenka31** [comment]
Hello, adding Python 3.11.5 on the list. I am on M1 Macbook.
